// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbor_MVd6b4qeNc3UWO1lacVUUH6StNqs',
    appId: '1:833836611445:android:5d8e891a25b9c5b50ec53c',
    messagingSenderId: '833836611445',
    projectId: 'food-4de46',
    storageBucket: 'food-4de46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJPuqYcFvOLiUXhwBI9bg5TUptdXxdS7Q',
    appId: '1:833836611445:ios:eefe3721a4c14cfd0ec53c',
    messagingSenderId: '833836611445',
    projectId: 'food-4de46',
    storageBucket: 'food-4de46.appspot.com',
    androidClientId: '833836611445-na48hse7t735crf42a5pm1n05h2ka1g5.apps.googleusercontent.com',
    iosClientId: '833836611445-ntdpveljt8bar3bdgver4ndgtedkbq91.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );
}
